# Generated by Django 5.1.dev20231003084436 on 2023-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
