# Generated by Django 5.1.dev20231003084436 on 2023-10-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentsmodel_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='star',
        ),
    ]
